import { isSupabaseConfigured, supabase } from '../lib/supabaseClient.js';
import { formatDisplayDate, getOpenItems, getPrimaryStatus, latestUpdatedAt, toDateInputValue } from '../lib/adminStatus.js';
import { routes } from '../lib/routes.js';

const state = { user:null, profile:null, units:[], itemTypes:[], selectedUnitId:'', map:null, markers:new Map(), tempMarker:null, placingLocation:false, realtimeChannel:null };
const q = (s) => document.querySelector(s);
const els = {
 loading:q('[data-admin-loading]'), denied:q('[data-access-denied]'), dashboard:q('[data-admin-dashboard]'), profileName:q('[data-profile-name]'), profileRole:q('[data-profile-role]'), signOut:q('[data-sign-out]'), message:q('[data-admin-message]'), map:q('#admin-map'), mapLegend:q('[data-map-legend]'), unitList:q('[data-unit-list]'), resultCount:q('[data-result-count]'), search:q('[data-unit-search]'), filter:q('[data-status-filter]'), clear:q('[data-clear-filters]'), archived:q('[data-show-archived]'), unitSelect:q('[data-unit-select]'), itemSelect:q('[data-item-select]'), status:q('[data-status-select]'), completed:q('[data-completed-date]'), due:q('[data-due-date]'), notes:q('[data-notes]'), existing:q('[data-existing-record]'), summary:q('[data-selected-summary]'), updateForm:q('[data-update-form]'), updateButton:q('[data-update-submit]'), unitEditor:q('[data-unit-editor]'), unitForm:q('[data-unit-form]'), unitId:q('[data-edit-unit-id]'), unitNumber:q('[data-edit-unit-number]'), unitDisplay:q('[data-edit-unit-display-name]'), unitBuilding:q('[data-edit-unit-building]'), unitLat:q('[data-edit-unit-lat]'), unitLng:q('[data-edit-unit-lng]'), unitNotes:q('[data-edit-unit-notes]'), unitActive:q('[data-edit-unit-active]'), newUnit:q('[data-new-unit]'), placeUnit:q('[data-place-unit]'), saveUnit:q('[data-save-unit]')
};

const show=(el,v)=>el?.classList.toggle('hidden',!v);
const canEditItems=()=>['president','admin','editor'].includes(state.profile?.role);
const canEditUnits=()=>['president','admin'].includes(state.profile?.role);
function escapeHtml(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function setMessage(text,type='info'){ if(!els.message)return; els.message.textContent=text; els.message.dataset.type=type; show(els.message,Boolean(text)); clearTimeout(setMessage.t); if(text)setMessage.t=setTimeout(()=>show(els.message,false),5000); }

async function requireSession(){
 if(!isSupabaseConfigured){show(els.loading,false);show(els.denied,true);els.denied.innerHTML='<p>Supabase is not configured. Add the public URL and anon key.</p>';return false}
 const {data,error}=await supabase.auth.getUser(); if(error||!data.user){location.assign(routes.adminLogin);return false}
 state.user=data.user;
 const r=await supabase.from('profiles').select('id,full_name,email,role,active').eq('user_id',data.user.id).maybeSingle();
 if(r.error||!r.data?.active){show(els.loading,false);show(els.denied,true);return false} state.profile=r.data; return true;
}

async function loadData(){
 const [u,t]=await Promise.all([
  supabase.from('units').select(`id,unit_number,display_name,building,lat,lng,notes,is_active,updated_at,unit_items(id,item_type_id,status,due_date,completed_date,notes,updated_at,item_types(id,slug,label,color,severity_rank))`).order('unit_number'),
  supabase.from('item_types').select('id,slug,label,color,severity_rank,is_active').eq('is_active',true).order('severity_rank')
 ]);
 if(u.error)throw u.error;if(t.error)throw t.error;state.units=u.data||[];state.itemTypes=t.data||[];
 renderFilters();renderOptions();renderLegend();renderAll();syncUpdateForm();
}
function renderFilters(){const cur=els.filter.value;els.filter.innerHTML=`<option value="all">All statuses</option><option value="clear">All clear</option><option value="unknown">Not reviewed / unknown</option>${state.itemTypes.map(x=>`<option value="${x.slug}">${escapeHtml(x.label)}</option>`).join('')}`;els.filter.value=[...els.filter.options].some(o=>o.value===cur)?cur:'all'}
function visibleUnits(){const search=els.search.value.trim().toLowerCase(), filter=els.filter.value, includeArchived=els.archived.checked;return state.units.filter(unit=>{
 if(!includeArchived&&!unit.is_active)return false;
 const matchSearch=!search||[unit.unit_number,unit.display_name,unit.building].filter(Boolean).some(v=>String(v).toLowerCase().includes(search));
 if(!matchSearch)return false;if(filter==='all')return true;
 const primary=getPrimaryStatus(unit,state.itemTypes);if(filter==='clear')return primary.slug==='clear';if(filter==='unknown')return primary.slug==='unknown'||(unit.unit_items||[]).some(i=>i.status==='unknown');
 return (unit.unit_items||[]).some(i=>(i.status==='open'||i.status==='unknown')&&i.item_types?.slug===filter);
 })}
function renderOptions(){const current=els.unitSelect.value||state.selectedUnitId;const active=state.units.filter(u=>u.is_active);els.unitSelect.innerHTML=`<option value="">Choose unit…</option>${active.map(u=>`<option value="${u.id}">Unit ${escapeHtml(u.unit_number)}</option>`).join('')}`;if(current&&active.some(u=>u.id===current))els.unitSelect.value=current;const item=els.itemSelect.value;els.itemSelect.innerHTML=`<option value="">Choose item…</option>${state.itemTypes.map(i=>`<option value="${i.id}">${escapeHtml(i.label)}</option>`).join('')}`;if(item)els.itemSelect.value=item}
function renderLegend(){els.mapLegend.innerHTML=`<span><i class="admin-status-dot" style="background:#4f8f5f"></i>All clear</span><span><i class="admin-status-dot" style="background:#6b7280"></i>Not reviewed</span>${state.itemTypes.map(i=>`<span><i class="admin-status-dot" style="background:${i.color}"></i>${escapeHtml(i.label)}</span>`).join('')}`}
function renderAll(){renderList();renderMap()}
function renderList(){const units=visibleUnits();els.resultCount.textContent=`${units.length} unit${units.length===1?'':'s'} shown`;if(!units.length){els.unitList.innerHTML='<p class="text-sm text-beach-slate/60">No units match these filters.</p>';return}
 els.unitList.innerHTML=units.map(unit=>{const p=getPrimaryStatus(unit,state.itemTypes), open=getOpenItems(unit), summary=open.length?open.map(i=>i.item_types?.label||i.status).join(', '):p.label;return `<button type="button" class="admin-unit-card w-full ${unit.id===state.selectedUnitId?'is-selected':''}" data-select-unit="${unit.id}"><div><div class="flex items-center"><i class="admin-status-dot" style="background:${p.color}"></i><h3 class="font-semibold">Unit ${escapeHtml(unit.unit_number)}${unit.is_active?'':' · Archived'}</h3></div><p class="mt-1 text-sm text-beach-slate/70">${escapeHtml(summary)}</p><small class="text-beach-slate/50">Updated ${formatDisplayDate(latestUpdatedAt(unit))}</small></div><span class="text-[10px] uppercase tracking-[.2em]">Select</span></button>`}).join('');
 els.unitList.querySelectorAll('[data-select-unit]').forEach(b=>b.addEventListener('click',()=>selectUnit(b.dataset.selectUnit)))}
function markerIcon(unit){const p=getPrimaryStatus(unit,state.itemTypes);return L.divIcon({className:'admin-unit-marker',html:`<span style="background:${p.color}" title="${escapeHtml(p.label)}"></span>`,iconSize:[22,22],iconAnchor:[11,11]})}
function renderMap(){if(!window.L||!els.map)return;if(!state.map){state.map=L.map('admin-map',{center:[29.7485,-85.3975],zoom:17,scrollWheelZoom:false});L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'Tiles &copy; Esri'}).addTo(state.map);state.map.on('click',e=>{if(!state.placingLocation||!canEditUnits())return;els.unitLat.value=e.latlng.lat.toFixed(6);els.unitLng.value=e.latlng.lng.toFixed(6);state.tempMarker?.remove();state.tempMarker=L.marker(e.latlng,{draggable:true}).addTo(state.map).on('dragend',d=>{const n=d.target.getLatLng();els.unitLat.value=n.lat.toFixed(6);els.unitLng.value=n.lng.toFixed(6)});state.placingLocation=false;setMessage('Location selected. Save the unit to keep it.','success')})}
 const currentIds=new Set(state.units.filter(u=>u.lat!=null&&u.lng!=null).map(u=>u.id));for(const [id,m] of state.markers){if(!currentIds.has(id)){m.remove();state.markers.delete(id)}}
 const visible=new Set(visibleUnits().map(u=>u.id));state.units.forEach(unit=>{if(unit.lat==null||unit.lng==null)return;let m=state.markers.get(unit.id), coords=[Number(unit.lat),Number(unit.lng)];if(!m){m=L.marker(coords,{icon:markerIcon(unit)}).on('click',()=>selectUnit(unit.id));state.markers.set(unit.id,m)}else{m.setLatLng(coords);m.setIcon(markerIcon(unit))}const p=getPrimaryStatus(unit,state.itemTypes);m.bindPopup(`<strong>Unit ${escapeHtml(unit.unit_number)}</strong><br>${escapeHtml(p.label)}`);visible.has(unit.id)?m.addTo(state.map):m.remove()})}
function selectUnit(id){const unit=state.units.find(u=>u.id===id);if(!unit)return;state.selectedUnitId=id;els.unitSelect.value=id;if(canEditUnits())populateUnitForm(unit);renderSelectedSummary(unit);syncUpdateForm();renderList();const m=state.markers.get(id);if(m&&state.map){state.map.setView(m.getLatLng(),Math.max(state.map.getZoom(),18));m.openPopup()}}
function renderSelectedSummary(unit){const p=getPrimaryStatus(unit,state.itemTypes), open=getOpenItems(unit);els.summary.innerHTML=`<strong>Unit ${escapeHtml(unit.unit_number)}</strong><br><span>${escapeHtml(p.label)}</span>${open.length?`<br><small>${open.length} open/unknown item${open.length===1?'':'s'}</small>`:''}`;show(els.summary,true)}
function currentRecord(){const unit=state.units.find(u=>u.id===els.unitSelect.value);return unit?.unit_items?.find(i=>(i.item_types?.id||i.item_type_id)===els.itemSelect.value)||null}
function syncUpdateForm(){const record=currentRecord();if(record){els.status.value=record.status;els.completed.value=toDateInputValue(record.completed_date);els.due.value=toDateInputValue(record.due_date);els.notes.value=record.notes||'';els.existing.textContent=`Editing existing record · updated ${formatDisplayDate(record.updated_at)}`;}else{els.status.value='unknown';els.completed.value='';els.due.value='';els.notes.value='';els.existing.textContent=els.unitSelect.value&&els.itemSelect.value?'No existing record. Saving will create one.':'Choose a unit and item.'}}
function populateUnitForm(u){els.unitId.value=u.id;els.unitNumber.value=u.unit_number||'';els.unitDisplay.value=u.display_name||'';els.unitBuilding.value=u.building||'';els.unitLat.value=u.lat??'';els.unitLng.value=u.lng??'';els.unitNotes.value=u.notes||'';els.unitActive.checked=Boolean(u.is_active)}
function resetUnitForm(){els.unitForm.reset();els.unitId.value='';els.unitActive.checked=true;state.tempMarker?.remove();state.tempMarker=null}
async function saveUnitItem(e){e.preventDefault();if(!canEditItems())return;const unitId=els.unitSelect.value,itemTypeId=els.itemSelect.value,status=els.status.value;if(!unitId||!itemTypeId){setMessage('Choose a unit and item.','error');return}if(status==='complete'&&!els.completed.value)els.completed.value=new Date().toISOString().slice(0,10);if(status==='not_applicable'){els.completed.value='';els.due.value=''}
 els.updateButton.disabled=true;const payload={unit_id:unitId,item_type_id:itemTypeId,status,completed_date:toDateInputValue(els.completed.value)||null,due_date:toDateInputValue(els.due.value)||null,notes:els.notes.value.trim()||null,updated_by:state.user.id};const {error}=await supabase.from('unit_items').upsert(payload,{onConflict:'unit_id,item_type_id'});els.updateButton.disabled=false;if(error){setMessage(error.message,'error');return}await loadData();selectUnit(unitId);els.itemSelect.value=itemTypeId;syncUpdateForm();setMessage('Unit update saved.','success')}
async function initializeUnitItems(unitId){const payload=state.itemTypes.map(t=>({unit_id:unitId,item_type_id:t.id,status:'unknown',updated_by:state.user.id}));if(!payload.length)return;const {error}=await supabase.from('unit_items').upsert(payload,{onConflict:'unit_id,item_type_id',ignoreDuplicates:true});if(error)throw error}
async function saveUnit(e){e.preventDefault();if(!canEditUnits())return;const num=els.unitNumber.value.trim(),lat=els.unitLat.value===''?null:Number(els.unitLat.value),lng=els.unitLng.value===''?null:Number(els.unitLng.value);if(!num){setMessage('Unit number is required.','error');return}if(!Number.isFinite(lat)||!Number.isFinite(lng)){setMessage('Choose valid coordinates.','error');return}const id=els.unitId.value;if(id&&!els.unitActive.checked&&!confirm('Archive this unit? It will be hidden unless “Show archived” is enabled.'))return;
 els.saveUnit.disabled=true;const payload={unit_number:num,display_name:els.unitDisplay.value.trim()||`Unit ${num}`,building:els.unitBuilding.value.trim()||null,lat,lng,notes:els.unitNotes.value.trim()||null,is_active:els.unitActive.checked};const req=id?supabase.from('units').update(payload).eq('id',id).select('id').single():supabase.from('units').insert(payload).select('id').single();const {data,error}=await req;if(error){els.saveUnit.disabled=false;setMessage(error.message,'error');return}try{if(!id)await initializeUnitItems(data.id)}catch(err){setMessage(`Unit created, but status initialization failed: ${err.message}`,'error')}els.saveUnit.disabled=false;resetUnitForm();await loadData();selectUnit(data.id);setMessage(id?'Unit saved.':'Unit added with all items marked Unknown.','success')}
function bind(){els.signOut.addEventListener('click',async()=>{await supabase.auth.signOut();location.assign(routes.adminLogin)});[els.search,els.filter,els.archived].forEach(el=>el.addEventListener(el===els.search?'input':'change',renderAll));els.clear.addEventListener('click',()=>{els.search.value='';els.filter.value='all';els.archived.checked=false;renderAll()});els.unitSelect.addEventListener('change',()=>{if(els.unitSelect.value)selectUnit(els.unitSelect.value);else{show(els.summary,false);syncUpdateForm()}});els.itemSelect.addEventListener('change',syncUpdateForm);els.status.addEventListener('change',()=>{if(els.status.value==='complete'&&!els.completed.value)els.completed.value=new Date().toISOString().slice(0,10);if(els.status.value==='not_applicable'){els.completed.value='';els.due.value=''}});els.updateForm.addEventListener('submit',saveUnitItem);els.unitForm.addEventListener('submit',saveUnit);els.newUnit.addEventListener('click',()=>{resetUnitForm();els.unitNumber.focus()});els.placeUnit.addEventListener('click',()=>{state.placingLocation=true;setMessage('Click the map to place the unit, then save it.')})}
function setupRealtime(){if(state.realtimeChannel)return;state.realtimeChannel=supabase.channel('admin-map-updates').on('postgres_changes',{event:'*',schema:'public',table:'unit_items'},loadData).on('postgres_changes',{event:'*',schema:'public',table:'units'},loadData).subscribe()}
async function init(){if(!await requireSession())return;els.profileName.textContent=state.profile.full_name||state.profile.email||state.user.email;els.profileRole.textContent=state.profile.role;show(els.loading,false);show(els.dashboard,true);show(els.unitEditor,canEditUnits());if(!canEditItems()){els.updateForm.querySelectorAll('input,select,textarea,button').forEach(x=>x.disabled=true);els.existing.textContent='Read-only access.'}bind();try{await loadData();setupRealtime()}catch(e){setMessage(e.message||'Unable to load admin data.','error')}}
init();
